/*
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using BybitAPI.Client;
using BybitAPI.Model;
using RestSharp;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BybitAPI.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICommonApi : IApiAccessor
    {
        #region Synchronous Operations

        /// <summary>
        /// Get Bybit OpenAPI announcements in the last 30 days in reverse order.
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns><see cref="Announcement"/></returns>
        Announcement CommonAnnouncements();

        /// <summary>
        /// Get Bybit OpenAPI announcements in the last 30 days in reverse order.
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Announcement</returns>
        ApiResponse<Announcement> CommonAnnouncementsWithHttpInfo();

        /// <summary>
        /// Query LCP info.
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbol">Contract type</param>
        /// <returns><see cref="LCPInfoBase"/></returns>
        LCPInfoBase CommonGetLcp(string symbol);

        /// <summary>
        /// Query LCP info.
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbol">Contract type</param>
        /// <returns>ApiResponse of LCPInfoBase</returns>
        ApiResponse<LCPInfoBase> CommonGetLcpWithHttpInfo(string symbol);

        /// <summary>
        /// Get bybit server time.
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns><see cref="ServerTime"/></returns>
        ServerTime CommonGetTime();

        /// <summary>
        /// Get bybit server time.
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ServerTime</returns>
        ApiResponse<ServerTime> CommonGetTimeWithHttpInfo();

        #endregion Synchronous Operations

        #region Asynchronous Operations

        /// <summary>
        /// Get Bybit OpenAPI announcements in the last 30 days in reverse order.
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of Announcement</returns>
        Task<Announcement> CommonAnnouncementsAsync();

        /// <summary>
        /// Get Bybit OpenAPI announcements in the last 30 days in reverse order.
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (Announcement)</returns>
        Task<ApiResponse<Announcement>> CommonAnnouncementsAsyncWithHttpInfo();

        /// <summary>
        /// Query LCP info.
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbol">Contract type</param>
        /// <returns>Task of LCPInfoBase</returns>
        Task<LCPInfoBase> CommonGetLcpAsync(string symbol);

        /// <summary>
        /// Query LCP info.
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbol">Contract type</param>
        /// <returns>Task of ApiResponse (LCPInfoBase)</returns>
        Task<ApiResponse<LCPInfoBase>> CommonGetLcpAsyncWithHttpInfo(string symbol);

        /// <summary>
        /// Get bybit server time.
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ServerTime</returns>
        Task<ServerTime> CommonGetTimeAsync();

        /// <summary>
        /// Get bybit server time.
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ServerTime)</returns>
        Task<ApiResponse<ServerTime>> CommonGetTimeAsyncWithHttpInfo();

        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CommonApi : ApiBase, ICommonApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CommonApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CommonApi(string basePath) : base(basePath) { }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CommonApi(Configuration? configuration = null) : base(configuration) { }

        /// <summary>
        /// Get Bybit OpenAPI announcements in the last 30 days in reverse order.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns><see cref="Announcement"/></returns>
        public Announcement CommonAnnouncements() => CommonAnnouncementsWithHttpInfo().Data;

        /// <summary>
        /// Get Bybit OpenAPI announcements in the last 30 days in reverse order.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Announcement</returns>
        public ApiResponse<Announcement> CommonAnnouncementsWithHttpInfo()
        {
            var localVarPath = "/v2/public/announcement";
            return CallApiWithHttpInfo<Announcement>(localVarPath, Method.GET);
        }

        /// <summary>
        /// Get Bybit OpenAPI announcements in the last 30 days in reverse order.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of Announcement</returns>
        public async Task<Announcement> CommonAnnouncementsAsync() => (await CommonAnnouncementsAsyncWithHttpInfo()).Data;

        /// <summary>
        /// Get Bybit OpenAPI announcements in the last 30 days in reverse order.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (Announcement)</returns>
        public Task<ApiResponse<Announcement>> CommonAnnouncementsAsyncWithHttpInfo()
        {
            var localVarPath = "/v2/public/announcement";
            return CallApiAsyncWithHttpInfo<Announcement>(localVarPath, Method.GET);
        }

        /// <summary>
        /// Query LCP info.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbol">Contract type</param>
        /// <returns><see cref="LCPInfoBase"/></returns>
        public LCPInfoBase CommonGetLcp(string symbol) => CommonGetLcpWithHttpInfo(symbol).Data;

        /// <summary>
        /// Query LCP info.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbol">Contract type</param>
        /// <returns>ApiResponse of LCPInfoBase</returns>
        public ApiResponse<LCPInfoBase> CommonGetLcpWithHttpInfo(string symbol)
        {
            // verify the required parameter 'symbol' is set
            if (symbol is null)
            {
                throw new ApiException(400, "Missing required parameter 'symbol' when calling CommonApi->CommonGetLcp");
            }

            var localVarPath = "/v2/private/account/lcp";
            var localVarQueryParams = new List<KeyValuePair<string, string>>();

            if (symbol is not null)
            {
                localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "symbol", symbol));
            }
            // authentication (timestamp) required
            if (!string.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("timestamp")))
            {
                localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "timestamp", Configuration.GetApiKeyWithPrefix("timestamp")));
            }
            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "api_key", Configuration.GetApiKeyWithPrefix("api_key")));
            }

            return CallApiWithHttpInfo<LCPInfoBase>(localVarPath, Method.GET, localVarQueryParams);
        }

        /// <summary>
        /// Query LCP info.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbol">Contract type</param>
        /// <returns>Task of LCPInfoBase</returns>
        public async Task<LCPInfoBase> CommonGetLcpAsync(string symbol) => (await CommonGetLcpAsyncWithHttpInfo(symbol)).Data;

        /// <summary>
        /// Query LCP info.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbol">Contract type</param>
        /// <returns>Task of ApiResponse (LCPInfoBase)</returns>
        public Task<ApiResponse<LCPInfoBase>> CommonGetLcpAsyncWithHttpInfo(string symbol)
        {
            // verify the required parameter 'symbol' is set
            if (symbol is null)
            {
                throw new ApiException(400, "Missing required parameter 'symbol' when calling CommonApi->CommonGetLcp");
            }

            var localVarPath = "/v2/private/account/lcp";
            var localVarQueryParams = new List<KeyValuePair<string, string>>();

            if (symbol is not null)
            {
                localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "symbol", symbol)); // query parameter
            }
            // authentication (timestamp) required
            if (!string.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("timestamp")))
            {
                localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "timestamp", Configuration.GetApiKeyWithPrefix("timestamp")));
            }
            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "api_key", Configuration.GetApiKeyWithPrefix("api_key")));
            }

            return CallApiAsyncWithHttpInfo<LCPInfoBase>(localVarPath, Method.GET, localVarQueryParams);
        }

        /// <summary>
        /// Get bybit server time.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns><see cref="ServerTime"/></returns>
        public ServerTime CommonGetTime() => CommonGetTimeWithHttpInfo().Data;

        /// <summary>
        /// Get bybit server time.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ServerTime</returns>
        public ApiResponse<ServerTime> CommonGetTimeWithHttpInfo()
        {
            var localVarPath = "/v2/public/time";
            return CallApiWithHttpInfo<ServerTime>(localVarPath, Method.GET);
        }

        /// <summary>
        /// Get bybit server time.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ServerTime</returns>
        public async Task<ServerTime> CommonGetTimeAsync() => (await CommonGetTimeAsyncWithHttpInfo()).Data;

        /// <summary>
        /// Get bybit server time.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ServerTime)</returns>
        public Task<ApiResponse<ServerTime>> CommonGetTimeAsyncWithHttpInfo()
        {
            var localVarPath = "/v2/public/time";
            return CallApiAsyncWithHttpInfo<ServerTime>(localVarPath, Method.GET);
        }
    }
}