/*
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using BybitAPI.Client;
using BybitAPI.Model;
using BybitAPI.Test.Api.Factory;
using NUnit.Framework;
using System.Net;
using System.Threading.Tasks;

namespace BybitAPI.Api.Test
{
    /// <summary>
    ///  Class for testing APIkeyApi
    /// </summary>
    [TestFixture]
    public class APIkeyApiTests
    {
        private APIkeyApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new APIkeyApi();
            var client = MockRestClientFactory.Create(HttpStatusCode.OK, json);
            instance.Configuration.ApiClient.RestClient = client;
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
        }

        /// <summary>
        /// Test an instance of APIkeyApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            Assert.IsInstanceOf<APIkeyApi>(instance, "instance is a APIkeyApi");
        }

        private readonly string json = @"{
    ""ret_code"": 0,
    ""ret_msg"": ""ok"",
    ""ext_code"": """",
    ""result"": [
        {
            ""api_key"": ""7GkMBBLTbGRfa0Nuh1"",
            ""type"": ""personal"",
            ""user_id"": 1,
            ""inviter_id"": 3,
            ""ips"": [
                ""*""
            ],
            ""note"": ""scalping_bot"",
            ""permissions"": [
                ""Order"",
                ""Position""
            ],
            ""created_at"": ""2019-10-28T13:22:39.000Z"",
            ""expired_at"": ""2020-01-28T13:22:39.000Z"",
            ""read_only"": false
        }
    ],
    ""ext_info"": null,
    ""time_now"": ""1577445138.790150"",
    ""rate_limit_status"": 99,
    ""rate_limit_reset_ms"": 1577445138812,
    ""rate_limit"": 100
}";

        /// <summary>
        /// Test APIkeyInfo
        /// </summary>
        [Test]
        public void APIkeyInfoTest()
        {
            // Arrange

            // Act
            var response = instance.APIkeyInfo();

            // Assert
            Assert.IsInstanceOf<APIKeyBase>(response, "response is APIKeyBase");
            Assert.That(response.RetCode, Is.EqualTo(0));
            Assert.That(response.RetMsg, Is.EqualTo("ok"));
            Assert.That(response.ExtCode, Is.EqualTo(""));
            Assert.That(response.ExtInfo, Is.Null);
            Assert.That(response.TimeNow, Is.EqualTo("1577445138.790150"));
            Assert.That(response.Result.Count, Is.EqualTo(1));
            Assert.That(response.Result[0].ApiKey, Is.EqualTo("7GkMBBLTbGRfa0Nuh1"));
            // TODO: and more...
        }

        [Test]
        public void APIkeyInfoWithHttpInfoTest()
        {
            // Arrange

            // Act
            var response = instance.APIkeyInfoWithHttpInfo();

            // Assert
            Assert.IsInstanceOf<ApiResponse<APIKeyBase>>(response, "response is ApiResponse<APIKeyBase>");
        }

        [Test()]
        public async Task APIkeyInfoAsyncTest()
        {
            // Arrange

            // Act
            var response = await instance.APIkeyInfoAsync();

            // Assert
            Assert.IsInstanceOf<APIKeyBase>(response, "response is APIKeyBase");
        }

        [Test()]
        public async Task APIkeyInfoAsyncWithHttpInfoTest()
        {
            // Arrange

            // Act
            var response = await instance.APIkeyInfoAsyncWithHttpInfo();

            // Assert
            Assert.IsInstanceOf<ApiResponse<APIKeyBase>>(response, "response is ApiResponse<APIKeyBase>");
        }
    }
}