/*
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

namespace BybitAPI.Model.Test
{
    /// <summary>
    ///  Class for testing AnnouncementInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnnouncementInfoTests
    {
        private AnnouncementInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AnnouncementInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
        }

        /// <summary>
        /// Test an instance of AnnouncementInfo
        /// </summary>
        [Test]
        public void AnnouncementInfoInstanceTest()
        {
            Assert.IsInstanceOf<AnnouncementInfo>(instance, "variable 'instance' is a AnnouncementInfo");
        }

        ///// <summary>
        ///// Test the property 'Id'
        ///// </summary>
        //[Test]
        //public void IdTest()
        //{
        //    // TODO unit test for the property 'Id'
        //}

        ///// <summary>
        ///// Test the property 'Title'
        ///// </summary>
        //[Test]
        //public void TitleTest()
        //{
        //    // TODO unit test for the property 'Title'
        //}

        ///// <summary>
        ///// Test the property 'Link'
        ///// </summary>
        //[Test]
        //public void LinkTest()
        //{
        //    // TODO unit test for the property 'Link'
        //}

        ///// <summary>
        ///// Test the property 'Summary'
        ///// </summary>
        //[Test]
        //public void SummaryTest()
        //{
        //    // TODO unit test for the property 'Summary'
        //}

        ///// <summary>
        ///// Test the property 'CreatedAt'
        ///// </summary>
        //[Test]
        //public void CreatedAtTest()
        //{
        //    // TODO unit test for the property 'CreatedAt'
        //}
    }
}