/*
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using BybitAPI.Model;
using NUnit.Framework;

namespace BybitAPI.Model.Test
{
    /// <summary>
    ///  Class for testing APIKeyInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class APIKeyInfoTests
    {
        private APIKeyInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new APIKeyInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
        }

        /// <summary>
        /// Test an instance of APIKeyInfo
        /// </summary>
        [Test]
        public void APIKeyInfoInstanceTest()
        {
            Assert.IsInstanceOf<APIKeyInfo>(instance, "variable 'instance' is a APIKeyInfo");
        }

        ///// <summary>
        ///// Test the property 'ApiKey'
        ///// </summary>
        //[Test]
        //public void ApiKeyTest()
        //{
        //    // TODO unit test for the property 'ApiKey'
        //}

        ///// <summary>
        ///// Test the property 'UserId'
        ///// </summary>
        //[Test]
        //public void UserIdTest()
        //{
        //    // TODO unit test for the property 'UserId'
        //}

        ///// <summary>
        ///// Test the property 'Ips'
        ///// </summary>
        //[Test]
        //public void IpsTest()
        //{
        //    // TODO unit test for the property 'Ips'
        //}

        ///// <summary>
        ///// Test the property 'Note'
        ///// </summary>
        //[Test]
        //public void NoteTest()
        //{
        //    // TODO unit test for the property 'Note'
        //}

        ///// <summary>
        ///// Test the property 'Permissions'
        ///// </summary>
        //[Test]
        //public void PermissionsTest()
        //{
        //    // TODO unit test for the property 'Permissions'
        //}

        ///// <summary>
        ///// Test the property 'CreatedAt'
        ///// </summary>
        //[Test]
        //public void CreatedAtTest()
        //{
        //    // TODO unit test for the property 'CreatedAt'
        //}

        ///// <summary>
        ///// Test the property 'ReadOnly'
        ///// </summary>
        //[Test]
        //public void ReadOnlyTest()
        //{
        //    // TODO unit test for the property 'ReadOnly'
        //}
    }
}