/*
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

namespace BybitAPI.Model.Test
{
    /// <summary>
    ///  Class for testing ConditionalRes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConditionalResTests
    {
        private ConditionalRes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ConditionalRes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
        }

        /// <summary>
        /// Test an instance of ConditionalRes
        /// </summary>
        [Test]
        public void ConditionalResInstanceTest()
        {
            Assert.IsInstanceOf<ConditionalRes>(instance, "variable 'instance' is a ConditionalRes");
        }

        ///// <summary>
        ///// Test the property 'StopOrderId'
        ///// </summary>
        //[Test]
        //public void StopOrderIdTest()
        //{
        //    // TODO unit test for the property 'StopOrderId'
        //}

        ///// <summary>
        ///// Test the property 'UserId'
        ///// </summary>
        //[Test]
        //public void UserIdTest()
        //{
        //    // TODO unit test for the property 'UserId'
        //}

        ///// <summary>
        ///// Test the property 'StopOrderStatus'
        ///// </summary>
        //[Test]
        //public void StopOrderStatusTest()
        //{
        //    // TODO unit test for the property 'StopOrderStatus'
        //}

        ///// <summary>
        ///// Test the property 'Symbol'
        ///// </summary>
        //[Test]
        //public void SymbolTest()
        //{
        //    // TODO unit test for the property 'Symbol'
        //}

        ///// <summary>
        ///// Test the property 'Side'
        ///// </summary>
        //[Test]
        //public void SideTest()
        //{
        //    // TODO unit test for the property 'Side'
        //}

        ///// <summary>
        ///// Test the property 'OrderType'
        ///// </summary>
        //[Test]
        //public void OrderTypeTest()
        //{
        //    // TODO unit test for the property 'OrderType'
        //}

        ///// <summary>
        ///// Test the property 'Price'
        ///// </summary>
        //[Test]
        //public void PriceTest()
        //{
        //    // TODO unit test for the property 'Price'
        //}

        ///// <summary>
        ///// Test the property 'Qty'
        ///// </summary>
        //[Test]
        //public void QtyTest()
        //{
        //    // TODO unit test for the property 'Qty'
        //}

        ///// <summary>
        ///// Test the property 'TimeInForce'
        ///// </summary>
        //[Test]
        //public void TimeInForceTest()
        //{
        //    // TODO unit test for the property 'TimeInForce'
        //}

        ///// <summary>
        ///// Test the property 'StopOrderType'
        ///// </summary>
        //[Test]
        //public void StopOrderTypeTest()
        //{
        //    // TODO unit test for the property 'StopOrderType'
        //}

        ///// <summary>
        ///// Test the property 'BasePrice'
        ///// </summary>
        //[Test]
        //public void BasePriceTest()
        //{
        //    // TODO unit test for the property 'BasePrice'
        //}

        ///// <summary>
        ///// Test the property 'StopPx'
        ///// </summary>
        //[Test]
        //public void StopPxTest()
        //{
        //    // TODO unit test for the property 'StopPx'
        //}

        ///// <summary>
        ///// Test the property 'OrderLinkId'
        ///// </summary>
        //[Test]
        //public void OrderLinkIdTest()
        //{
        //    // TODO unit test for the property 'OrderLinkId'
        //}

        ///// <summary>
        ///// Test the property 'CreatedAt'
        ///// </summary>
        //[Test]
        //public void CreatedAtTest()
        //{
        //    // TODO unit test for the property 'CreatedAt'
        //}

        ///// <summary>
        ///// Test the property 'UpdatedAt'
        ///// </summary>
        //[Test]
        //public void UpdatedAtTest()
        //{
        //    // TODO unit test for the property 'UpdatedAt'
        //}
    }
}