/*
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

namespace BybitAPI.Test
{
    /// <summary>
    ///  Class for testing LinearSwitchModeResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LinearSwitchModeResultTests
    {
        // TODO uncomment below to declare an instance variable for LinearSwitchModeResult
        //private LinearSwitchModeResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LinearSwitchModeResult
            //instance = new LinearSwitchModeResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
        }

        /// <summary>
        /// Test an instance of LinearSwitchModeResult
        /// </summary>
        [Test]
        public void LinearSwitchModeResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LinearSwitchModeResult
            //Assert.IsInstanceOfType<LinearSwitchModeResult> (instance, "variable 'instance' is a LinearSwitchModeResult");
        }

        /// <summary>
        /// Test the property 'TpSlMode'
        /// </summary>
        [Test]
        public void TpSlModeTest()
        {
            // TODO unit test for the property 'TpSlMode'
        }
    }
}
