/*
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

namespace BybitAPI.Model.Test
{
    /// <summary>
    ///  Class for testing LinearSwitchModeResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LinearSwitchModeResultTests
    {
        private LinearSwitchModeResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init() => instance = new LinearSwitchModeResult();

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
        }

        /// <summary>
        /// Test an instance of LinearSwitchModeResult
        /// </summary>
        [Test]
        public void LinearSwitchModeResultInstance_ShouldBeCreated() => Assert.IsInstanceOf<LinearSwitchModeResult>(instance, "variable 'instance' is a LinearSwitchModeResult");

        ///// <summary>
        ///// Test the property 'TpSlMode'
        ///// </summary>
        //[Test]
        //public void TpSlModeTest()
        //{
        //    // TODO unit test for the property 'TpSlMode'
        //}
    }
}