/*
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

namespace BybitAPI.Model.Test
{
    /// <summary>
    ///  Class for testing OpenInterestInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OpenInterestInfoTests
    {
        private OpenInterestInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init() => instance = new OpenInterestInfo();

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
        }

        /// <summary>
        /// Test an instance of OpenInterestInfo
        /// </summary>
        [Test]
        public void OpenInterestInfoInstance_ShouldBeCreated() => Assert.IsInstanceOf<OpenInterestInfo>(instance, "variable 'instance' is a OpenInterestInfo");

        ///// <summary>
        ///// Test the property 'OpenInterest'
        ///// </summary>
        //[Test]
        //public void OpenInterestTest()
        //{
        //    // TODO unit test for the property 'OpenInterest'
        //}

        ///// <summary>
        ///// Test the property 'Timestamp'
        ///// </summary>
        //[Test]
        //public void TimestampTest()
        //{
        //    // TODO unit test for the property 'Timestamp'
        //}

        ///// <summary>
        ///// Test the property 'Symbol'
        ///// </summary>
        //[Test]
        //public void SymbolTest()
        //{
        //    // TODO unit test for the property 'Symbol'
        //}
    }
}