/*
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using BybitAPI.Model;
using NUnit.Framework;

namespace BybitAPI.Model.Test
{
    /// <summary>
    ///  Class for testing OrderCancelAllRes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderCancelAllResTests
    {
        private OrderCancelAllRes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OrderCancelAllRes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
        }

        /// <summary>
        /// Test an instance of OrderCancelAllRes
        /// </summary>
        [Test]
        public void OrderCancelAllResInstanceTest()
        {
            Assert.IsInstanceOf<OrderCancelAllRes>(instance, "variable 'instance' is a OrderCancelAllRes");
        }

        ///// <summary>
        ///// Test the property 'ClOrdID'
        ///// </summary>
        //[Test]
        //public void ClOrdIDTest()
        //{
        //    // TODO unit test for the property 'ClOrdID'
        //}

        ///// <summary>
        ///// Test the property 'UserId'
        ///// </summary>
        //[Test]
        //public void UserIdTest()
        //{
        //    // TODO unit test for the property 'UserId'
        //}

        ///// <summary>
        ///// Test the property 'Side'
        ///// </summary>
        //[Test]
        //public void SideTest()
        //{
        //    // TODO unit test for the property 'Side'
        //}

        ///// <summary>
        ///// Test the property 'OrderType'
        ///// </summary>
        //[Test]
        //public void OrderTypeTest()
        //{
        //    // TODO unit test for the property 'OrderType'
        //}

        ///// <summary>
        ///// Test the property 'Price'
        ///// </summary>
        //[Test]
        //public void PriceTest()
        //{
        //    // TODO unit test for the property 'Price'
        //}

        ///// <summary>
        ///// Test the property 'Qty'
        ///// </summary>
        //[Test]
        //public void QtyTest()
        //{
        //    // TODO unit test for the property 'Qty'
        //}

        ///// <summary>
        ///// Test the property 'TimeInForce'
        ///// </summary>
        //[Test]
        //public void TimeInForceTest()
        //{
        //    // TODO unit test for the property 'TimeInForce'
        //}

        ///// <summary>
        ///// Test the property 'CreateType'
        ///// </summary>
        //[Test]
        //public void CreateTypeTest()
        //{
        //    // TODO unit test for the property 'CreateType'
        //}

        ///// <summary>
        ///// Test the property 'OrderStatus'
        ///// </summary>
        //[Test]
        //public void OrderStatusTest()
        //{
        //    // TODO unit test for the property 'OrderStatus'
        //}

        ///// <summary>
        ///// Test the property 'LeavesQty'
        ///// </summary>
        //[Test]
        //public void LeavesQtyTest()
        //{
        //    // TODO unit test for the property 'LeavesQty'
        //}

        ///// <summary>
        ///// Test the property 'LeavesValue'
        ///// </summary>
        //[Test]
        //public void LeavesValueTest()
        //{
        //    // TODO unit test for the property 'LeavesValue'
        //}

        ///// <summary>
        ///// Test the property 'CreatedAt'
        ///// </summary>
        //[Test]
        //public void CreatedAtTest()
        //{
        //    // TODO unit test for the property 'CreatedAt'
        //}

        ///// <summary>
        ///// Test the property 'UpdatedAt'
        ///// </summary>
        //[Test]
        //public void UpdatedAtTest()
        //{
        //    // TODO unit test for the property 'UpdatedAt'
        //}

        ///// <summary>
        ///// Test the property 'CrossStatus'
        ///// </summary>
        //[Test]
        //public void CrossStatusTest()
        //{
        //    // TODO unit test for the property 'CrossStatus'
        //}

        ///// <summary>
        ///// Test the property 'CrossSeq'
        ///// </summary>
        //[Test]
        //public void CrossSeqTest()
        //{
        //    // TODO unit test for the property 'CrossSeq'
        //}
    }
}